### ISSUE TITLE
Add support for Inferno

### ISSUE THREAD

**Issue by slmgc** [Aweary/ssr-benchmarks#2]
https://github.com/trueadm/inferno
It also has a compatibility layer `inferno-compat`.
I think it's better to use the latest 1.0.0-beta for comparison.

**Comment by aweary** [comment]
Added in https://github.com/Aweary/ssr-benchmarks/pull/4 🎉

**Comment by slmgc** [comment]
@Aweary I think it's a good idea to mention Inferno in the documentation
